name: Version Bump and Tag

on:
  # Trigger the workflow on push only for the master branch
  push:
    branches:
      - master

env:
  NODE_ENV: 'development'
  GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  bump:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
 
      - name: Bump Version
        uses: joshuef/auto-rust-version-bumper@v1
        with:
          personal-access-token: $PERSONAL_ACCESS_TOKEN
